🐛 Fix transaction conflict when generating multiple QR codes
Why:
- This is a regression of d0f74b7fb71be8c5509bcd0c2a6a65ef76e993cb
- Though the new SSR API doesn't call current-state-for-request similar
  to the old SPA API, the same transaction conflict issue happens:

ERROR:  deadlock detected
DETAIL:  Process 5463 waits for ShareRowExclusiveLock on relation 405129 of database 16384; blocked by process 5460.
	Process 5460 waits for ShareRowExclusiveLock on relation 405129 of database 16384; blocked by process 5463.
	Process 5463: insert into event (stream_id, stream_revision, data)
	values ($1, $2, $3::jsonb)
	returning global_revision, stream_revision
	Process 5460: insert into event (stream_id, stream_revision, data)
	values ($1, $2, $3::jsonb)
	returning global_revision, stream_revision
HINT:  See server log for query details.
CONTEXT:  SQL statement "lock table test_territorybro.event in share row exclusive mode"
	PL/pgSQL function prepare_new_event() line 9 at SQL statement
STATEMENT:  insert into event (stream_id, stream_revision, data)
	values ($1, $2, $3::jsonb)
	returning global_revision, stream_revision

- One theory was that territory-bro.infra.event-store/check-new-stream
  in the reference checkers acquires a read lock on the event table, and
  that produces a deadlock. That however had no effect.
- The current theory is that the insert statement acquires a lock on the
  event table, and the stricter lock inside the trigger happens after
  that, producing a deadlock.
- Confusingly, it was necessary to lower the transaction isolation level
  from serializable down to read committed. Otherwise, we would get
  transaction conflicts like:

ERROR:  could not serialize access due to read/write dependencies among transactions
DETAIL:  Reason code: Canceled on identification as a pivot, during write.
HINT:  The transaction might succeed if retried.
CONTEXT:  SQL statement "insert into stream (stream_id, entity_type, congregation)
	        values (new.stream_id, new_entity_type, new_congregation)
	        on conflict (stream_id) do update
	            set entity_type  = new_entity_type,
	                congregation = new_congregation"
	PL/pgSQL function prepare_new_event() line 53 at SQL statement
STATEMENT:  insert into event (stream_id, stream_revision, data)
	values ($1, $2, $3::jsonb)
	returning global_revision, stream_revision