🐛 Fix crash when recreating a GIS entry with the same ID
Why:
- The application crashed if a GIS entity was created with the same ID
  as before (a sequence of insert, delete, insert). This is allowed by
  the validate_gis_change trigger when the congregation and entity type
  are the same as before for that stream.
- The validate_gis_change trigger already should do enough checks to
  ensure ID uniqueness. It only allows ID reused with the congregation
  and entity type are the same. Thus it should be safe to disable ID
  validation in the command schema.
- We considered adding an undelete command and tagging deleted entities
  with `:deleted? true` in the state. But an additional command would
  even further increase the duplication between insert and update,
  whereas an upsert would reduce the code. Also a `:deleted?` flag would
  need to be filtered when reading the state, which would make every
  read more complicated.

territory_bro.WriteConflictException: Event stream ddf1e698-22a4-4951-b9bd-917f1e2c0163 already exists
        at territory_bro.infra.event_store$check_new_stream.invokeStatic(event_store.clj:57)
        at territory_bro.infra.event_store$check_new_stream.invoke(event_store.clj:55)
        at territory_bro.dispatcher$reference_checkers$fn__11312.invoke(dispatcher.clj:60)
        at territory_bro.infra.foreign_key.References$postcondition__7851.invoke(foreign_key.clj:25)
        at schema.spec.variant.VariantSpec$fn__4205.invoke(variant.clj:56)
        at schema.spec.collection$element_transformer$fn__4243$fn__4244.invoke(collection.clj:36)
        at schema.core.MapEntry$fn__5062.invoke(core.clj:766)
        at schema.spec.collection$element_transformer$fn__4243.invoke(collection.clj:36)
        at schema.spec.collection$element_transformer$fn__4243.invoke(collection.clj:36)
        at schema.spec.collection.CollectionSpec$fn__4275.invoke(collection.clj:79)
        at schema.spec.collection$element_transformer$fn__4243$fn__4244.invoke(collection.clj:36)
        at schema.core$map_elements$iter__5096__5100$fn__5101$fn__5112.invoke(core.clj:816)
        at schema.spec.collection$element_transformer$fn__4243.invoke(collection.clj:36)
        at schema.spec.collection$element_transformer$fn__4243.invoke(collection.clj:36)
        at schema.spec.collection$element_transformer$fn__4243.invoke(collection.clj:36)
        at schema.spec.collection$element_transformer$fn__4243.invoke(collection.clj:36)
        at schema.spec.collection$element_transformer$fn__4243.invoke(collection.clj:36)
        at schema.spec.collection$element_transformer$fn__4243.invoke(collection.clj:36)
        at schema.spec.collection$element_transformer$fn__4243.invoke(collection.clj:36)
        at schema.spec.collection.CollectionSpec$fn__4275.invoke(collection.clj:79)
        at schema.spec.variant$option_step$fn__4174.invoke(variant.clj:28)
        at schema.spec.variant$option_step$fn__4174.invoke(variant.clj:31)
        at schema.spec.variant$option_step$fn__4174.invoke(variant.clj:31)
        at schema.spec.variant$option_step$fn__4174.invoke(variant.clj:31)
        at schema.spec.variant$option_step$fn__4174.invoke(variant.clj:31)
        at schema.spec.variant$option_step$fn__4174.invoke(variant.clj:31)
        at schema.spec.variant$option_step$fn__4174.invoke(variant.clj:31)
        at schema.spec.variant$option_step$fn__4174.invoke(variant.clj:31)
        at schema.spec.variant$option_step$fn__4174.invoke(variant.clj:31)
        at schema.spec.variant$option_step$fn__4174.invoke(variant.clj:31)
        at schema.spec.variant$option_step$fn__4174.invoke(variant.clj:31)
        at schema.spec.variant$option_step$fn__4174.invoke(variant.clj:31)
        at schema.spec.variant$option_step$fn__4174.invoke(variant.clj:31)
        at schema.spec.variant$option_step$fn__4174.invoke(variant.clj:31)
        at schema.spec.variant$option_step$fn__4174.invoke(variant.clj:31)
        at schema.spec.variant$option_step$fn__4174.invoke(variant.clj:31)
        at schema.spec.variant$option_step$fn__4174.invoke(variant.clj:31)
        at schema.spec.variant$option_step$fn__4174.invoke(variant.clj:31)
        at schema.spec.variant$option_step$fn__4174.invoke(variant.clj:31)
        at schema.spec.variant$option_step$fn__4174.invoke(variant.clj:31)
        at schema.spec.variant$option_step$fn__4174.invoke(variant.clj:31)
        at schema.spec.variant.VariantSpec$fn__4209.invoke(variant.clj:59)
        at clojure.core$comp$fn__5807.invoke(core.clj:2569)
        at schema.core$validator$fn__4372.invoke(core.clj:154)
        at territory_bro.commands$validate_command.invokeStatic(commands.clj:263)
        at territory_bro.commands$validate_command.invoke(commands.clj:259)
        at territory_bro.dispatcher$validate_command.invokeStatic(dispatcher.clj:65)
        at territory_bro.dispatcher$validate_command.invoke(dispatcher.clj:63)
        at territory_bro.dispatcher$command_BANG_.invokeStatic(dispatcher.clj:165)
        at territory_bro.dispatcher$command_BANG_.invoke(dispatcher.clj:161)
        at territory_bro.gis.gis_sync$process_changes_BANG_$fn__11834.invoke(gis_sync.clj:27)
        at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
        at clojure.core$reduce.invokeStatic(core.clj:6827)
        at clojure.core$reduce.invoke(core.clj:6810)
        at territory_bro.gis.gis_sync$process_changes_BANG_.invokeStatic(gis_sync.clj:25)
        at territory_bro.gis.gis_sync$process_changes_BANG_.invoke(gis_sync.clj:22)
        at territory_bro.gis.gis_sync$refresh_BANG_$fn__11838.invoke(gis_sync.clj:39)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:807)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:852)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
        at territory_bro.gis.gis_sync$refresh_BANG_.invokeStatic(gis_sync.clj:38)
        at territory_bro.gis.gis_sync$refresh_BANG_.invoke(gis_sync.clj:36)
        at territory_bro.infra.poller.AsyncPoller$fn__11588.invoke(poller.clj:26)
        at territory_bro.infra.executors$run_safely_BANG_.invokeStatic(executors.clj:17)
        at territory_bro.infra.executors$run_safely_BANG_.invoke(executors.clj:15)
        at territory_bro.infra.executors$safe_task$fn__11527.invoke(executors.clj:28)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)