🐛 Fix crash when viewing a demo territory after opening a share
Why:
- It used to crash in territory-bro.api/current-user-id because
  territory-bro.infra.authentication/*user* was unbound. There was no
  error if the user first visited the demo, without having opened a
  share. Exception stack trace:

java.lang.AssertionError: Assert failed: id
	at territory_bro.api$current_user_id.invokeStatic(api.clj:172)
	at territory_bro.api$current_user_id.invoke(api.clj:169)
	at territory_bro.api$enrich_state_for_request.invokeStatic(api.clj:180)
	at territory_bro.api$enrich_state_for_request.invoke(api.clj:175)
	at territory_bro.api$state_for_request.invokeStatic(api.clj:184)
	at territory_bro.api$state_for_request.invoke(api.clj:182)
	at territory_bro.api$get_demo_territory.invokeStatic(api.clj:271)
	at territory_bro.api$get_demo_territory.invoke(api.clj:267)
	at territory_bro.api$fn__24497.invokeStatic(api.clj:514)
	at territory_bro.api$fn__24497.invoke(api.clj:514)
	at compojure.core$wrap_response$fn__15700.invoke(core.clj:158)
	at compojure.core$pre_init$fn__15801.invoke(core.clj:331)
	at ring.middleware.http_response$wrap_http_response$fn__15864.invoke(http_response.clj:19)
	at compojure.core$pre_init$fn__15803$fn__15806.invoke(core.clj:338)
	at compojure.core$pre_init$fn__15801.invoke(core.clj:331)
        ...