🐛 Fix GIS sync when the ID column is changed
Why:
- GIS sync used to crash in command validation with :no-such-territory
  error when there was an UPDATE event that changed the ID column. The
  fix is to split the problematic GIS change into a DELETE and INSERT.
- There is some interaction with the replacement ID feature, so that
  will need to be tested further, but this fix is enough to make the app
  again operational.

{:command/type :territory.command/update-territory,
 :command/user #uuid "eb9ef906-3661-4e49-acad-608b8cba0a4a",
 :command/system "territory-bro.gis.gis-change",
 :command/time #object[java.time.Instant 0x5974b233 "2021-04-28T15:05:47.147705Z"],
 :congregation/id #uuid "8e5255ff-2bee-40c5-8ad7-16f24fca2db6",
 :gis-change/id 9202,
 :territory/addresses "...",
 :territory/id #uuid "6c55dbd9-4e94-4eeb-a828-1ea8b98e40bb",
 :territory/location "MULTIPOLYGON(((...",
 :territory/meta {},
 :territory/number "57",
 :territory/region ""}

territory_bro.ValidationException: [[:no-such-territory #uuid "8e5255ff-2bee-40c5-8ad7-16f24fca2db6" #uuid "6c55dbd9-4e94-4eeb-a828-1ea8b98e40bb"]]
	at territory_bro.domain.territory$check_territory_exists.invokeStatic(territory.clj:38)
	at territory_bro.domain.territory$check_territory_exists.invoke(territory.clj:37)
	at territory_bro.dispatcher$reference_checkers$fn__11319.invoke(dispatcher.clj:50)
	at territory_bro.infra.foreign_key.References$postcondition__7851.invoke(foreign_key.clj:25)
	at schema.spec.variant.VariantSpec$fn__4205.invoke(variant.clj:56)
	at schema.spec.collection$element_transformer$fn__4243$fn__4244.invoke(collection.clj:36)
	at schema.core.MapEntry$fn__5062.invoke(core.clj:766)
	at schema.spec.collection$element_transformer$fn__4243.invoke(collection.clj:36)
	at schema.spec.collection$element_transformer$fn__4243.invoke(collection.clj:36)
	at schema.spec.collection.CollectionSpec$fn__4275.invoke(collection.clj:79)
	at schema.spec.collection$element_transformer$fn__4243$fn__4244.invoke(collection.clj:36)
	at schema.core$map_elements$iter__5096__5100$fn__5101$fn__5112.invoke(core.clj:816)
	at schema.spec.collection$element_transformer$fn__4243.invoke(collection.clj:36)
	at schema.spec.collection$element_transformer$fn__4243.invoke(collection.clj:36)
	at schema.spec.collection$element_transformer$fn__4243.invoke(collection.clj:36)
	at schema.spec.collection$element_transformer$fn__4243.invoke(collection.clj:36)
	at schema.spec.collection$element_transformer$fn__4243.invoke(collection.clj:36)
	at schema.spec.collection$element_transformer$fn__4243.invoke(collection.clj:36)
	at schema.spec.collection$element_transformer$fn__4243.invoke(collection.clj:36)
	at schema.spec.collection$element_transformer$fn__4243.invoke(collection.clj:36)
	at schema.spec.collection$element_transformer$fn__4243.invoke(collection.clj:36)
	at schema.spec.collection$element_transformer$fn__4243.invoke(collection.clj:36)
	at schema.spec.collection$element_transformer$fn__4243.invoke(collection.clj:36)
	at schema.spec.collection$element_transformer$fn__4243.invoke(collection.clj:36)
	at schema.spec.collection.CollectionSpec$fn__4275.invoke(collection.clj:79)
	at schema.spec.variant$option_step$fn__4174.invoke(variant.clj:28)
	at schema.spec.variant$option_step$fn__4174.invoke(variant.clj:31)
	at schema.spec.variant.VariantSpec$fn__4209.invoke(variant.clj:59)
	at clojure.core$comp$fn__5807.invoke(core.clj:2569)
	at schema.core$validator$fn__4372.invoke(core.clj:154)
	at territory_bro.commands$validate_command.invokeStatic(commands.clj:263)
	at territory_bro.commands$validate_command.invoke(commands.clj:259)
	at territory_bro.dispatcher$validate_command.invokeStatic(dispatcher.clj:65)
	at territory_bro.dispatcher$validate_command.invoke(dispatcher.clj:63)
	at territory_bro.dispatcher$command_BANG_.invokeStatic(dispatcher.clj:165)
	at territory_bro.dispatcher$command_BANG_.invoke(dispatcher.clj:161)
	at territory_bro.gis.gis_sync$process_changes_BANG_.invokeStatic(gis_sync.clj:40)
	at territory_bro.gis.gis_sync$process_changes_BANG_.invoke(gis_sync.clj:24)
	at territory_bro.gis.gis_sync$refresh_BANG_$fn__11840.invoke(gis_sync.clj:50)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:807)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:852)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
	at territory_bro.gis.gis_sync$refresh_BANG_.invokeStatic(gis_sync.clj:49)
	at territory_bro.gis.gis_sync$refresh_BANG_.invoke(gis_sync.clj:47)
	at territory_bro.main$migrate_database_BANG_.invokeStatic(main.clj:52)
	at territory_bro.main$migrate_database_BANG_.invoke(main.clj:45)
	at territory_bro.main$start_app.invokeStatic(main.clj:70)
	at territory_bro.main$start_app.invoke(main.clj:64)
	at territory_bro.main$_main$fn__18254.invoke(main.clj:80)
	at territory_bro.main$_main.invokeStatic(main.clj:79)
	at territory_bro.main$_main.doInvoke(main.clj:78)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at territory_bro.main.main(Unknown Source)