🔧 Fix OutOfMemoryError on startup
Why:
- When the app container started, it often failed with
  "OutOfMemoryError: Java heap space" (see below) when the container had
  a memory limit of 500MB.
- Enabling -XX:+PrintCommandLineFlags showed the effective memory
  settings -XX:InitialHeapSize=8192000 (8MB), -XX:MaxHeapSize=131072000
  (128MB), -XX:MinHeapSize=6815736 (6MB).
- The JVM defaults the maximum heap size to 1/4 of physical memory.
    https://docs.oracle.com/en/java/javase/17/gctuning/ergonomics.html
- The solution is to tell the JVM to use more memory. We opted to
  setting InitialRAMPercentage and MaxRAMPercentage (with the
  recommended value 70) instead of a fixed memory limit, so that the
  limit could be increased in production without rebuild as the
  in-memory database increases in size over time.
    https://www.alibabacloud.com/help/en/sae/use-cases/best-practices-for-jvm-heap-size-configuration

java.lang.OutOfMemoryError: Java heap space
	at java.base/java.lang.StringLatin1.newString(Unknown Source)
	at java.base/java.lang.String.substring(Unknown Source)
	at java.base/java.lang.Class.getPackageName(Unknown Source)
	at java.base/sun.invoke.util.VerifyAccess.isSamePackage(Unknown Source)
	at java.base/sun.invoke.util.VerifyAccess.isClassAccessible(Unknown Source)
	at java.base/java.lang.invoke.MethodHandles$Lookup.isClassAccessible(Unknown Source)
	at java.base/java.lang.invoke.MethodHandles$Lookup.checkSymbolicClass(Unknown Source)
	at java.base/java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(Unknown Source)
	at java.base/java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(Unknown Source)
	at java.base/java.util.ResourceBundle$ResourceBundleControlProviderHolder.<clinit>(Unknown Source)
	at java.base/java.util.ResourceBundle.getDefaultControl(Unknown Source)
	at java.base/java.util.ResourceBundle.getDefaultControl(Unknown Source)
	at java.base/java.util.ResourceBundle.getBundle(Unknown Source)
	at org.postgresql.util.GT.<init>(GT.java:35)
	at org.postgresql.util.GT.<clinit>(GT.java:24)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2383)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:194)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:137)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:1090)
	at clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:1084)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1106)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1093)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1182)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1160)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)