🥅 Handle incomplete Ring requests gracefully
Why:
- Fixes the following NPE, when tests use incomplete request objects,
  which are missing the mandatory :uri key.

2024-07-26 00:55:14,405 [clojure-agent-send-off-pool-0] ERROR territory-bro.ui.error-page - Error in building the layout model
java.lang.NullPointerException: Cannot invoke "Object.toString()" because "s" is null
	at clojure.string$replace.invokeStatic(string.clj:101)
	at clojure.string$replace.invoke(string.clj:75)
	at ring.util.codec$url_encode.invokeStatic(codec.clj:66)
	at ring.util.codec$url_encode.invoke(codec.clj:60)
	at ring.util.codec$url_encode.invokeStatic(codec.clj:64)
	at ring.util.codec$url_encode.invoke(codec.clj:60)
	at territory_bro.infra.auth0$login_url.invokeStatic(auth0.clj:106)
	at territory_bro.infra.auth0$login_url.invoke(auth0.clj:105)
	at territory_bro.ui.layout$model_BANG_.invokeStatic(layout.clj:32)
	at territory_bro.ui.layout$model_BANG_.invoke(layout.clj:19)
	at territory_bro.ui.error_page$safe_page$fn__72654.invoke(error_page.clj:18)
	at territory_bro.ui.error_page$safe_page.invokeStatic(error_page.clj:16)
	at territory_bro.ui.error_page$safe_page.invoke(error_page.clj:15)
	at territory_bro.ui.error_page_test$fn__82149.invokeStatic(error_page_test.clj:99)
	at territory_bro.ui.error_page_test$fn__82149.invoke(error_page_test.clj:90)