👷 Upgrade to Node.js 18
Why:
- The Docker build used to fail because of too old Debian version:

E: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/main/binary-amd64/Packages  404  Not Found
E: Failed to fetch http://deb.debian.org/debian/dists/stretch/main/binary-amd64/Packages  404  Not Found
E: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/main/binary-amd64/Packages  404  Not Found

- Node.js 18 is the current LTS version.
- Webpack fails with the current Node.js version, so the
  `--openssl-legacy-provider` option is needed as a workaround:

node:internal/crypto/hash:69
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/project/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/project/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/project/node_modules/webpack/lib/NormalModule.js:471:10)
    at /project/node_modules/webpack/lib/NormalModule.js:503:5
    at /project/node_modules/webpack/lib/NormalModule.js:358:12
    at /project/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/project/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/project/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /project/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/project/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /project/node_modules/babel-loader/lib/index.js:59:71
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}