🐛 Fix authentication mis-detecting its redirect URI
Why:
- The login-callback failed in prod with the error "The redirect URI is
  wrong. You sent https://beta.territorybro.com:80, and we expected
  https://beta.territorybro.com".
- The Auth0 library uses javax.servlet.http.HttpServletRequest#getRequestURL
  to verify the callback URL, but it incorrectly produced
  "https://beta.territorybro.com:80/login-callback" because the Ring
  request had the values:
    {:request-method :get
     :scheme :https
     :server-name "beta.territorybro.com"
     :server-port 80
     :uri "/login-callback"}
- It's not known where the server-port 80 came from. Jetty was running
  in port 8080 and the reverse proxy was in https port 443. The most
  reasonable explanation is that the server-port came from the default
  http port, because Jetty was running using http.
- As a workaround we disable any auto-detection based on the request
  object, and always use the server's public URL from the configuration.

2024-07-14 18:22:59,762 [qtp513113647-29] WARN  territory-bro.infra.auth0 - Login failed
com.auth0.IdentityVerificationException: An error occurred while exchanging the authorization code.
	at com.auth0.RequestProcessor.getVerifiedTokens(RequestProcessor.java:238)
	at com.auth0.RequestProcessor.process(RequestProcessor.java:196)
	at com.auth0.AuthenticationController.handle(AuthenticationController.java:306)
	at territory_bro.infra.auth0$login_callback_handler.invokeStatic(auth0.clj:142)
	at territory_bro.infra.auth0$login_callback_handler.invoke(auth0.clj:138)
	at territory_bro.ui$wrap_json_api_compat$fn__27997.invoke(ui.clj:30)
	at ring.middleware.http_response$wrap_http_response$fn__14946.invoke(http_response.clj:19)
	at territory_bro.ui$wrap_current_user$fn__28000$fn__28001.invoke(ui.clj:35)
	at territory_bro.infra.authentication$with_user_STAR_.invokeStatic(authentication.clj:34)
	at territory_bro.infra.authentication$with_user_STAR_.invoke(authentication.clj:31)
	at territory_bro.ui$wrap_current_user$fn__28000.invoke(ui.clj:34)
	at territory_bro.ui.i18n$wrap_current_language$fn__16548.invoke(i18n.clj:48)
	at territory_bro.infra.auth0$wrap_redirect_to_login$fn__12371.invoke(auth0.clj:110)
	at territory_bro.ui.html$wrap_page_path$fn__16527.invoke(html.clj:83)
	at reitit.ring$ring_handler$fn__19766.invoke(ring.cljc:357)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:33)
	at clojure.lang.RestFn.invoke(RestFn.java:411)
	at clojure.lang.Var.invoke(Var.java:386)
	at compojure.core$routing$fn__2397.invoke(core.clj:185)
	at clojure.core$some.invokeStatic(core.clj:2718)
	at clojure.core$some.invoke(core.clj:2709)
	at compojure.core$routing.invokeStatic(core.clj:185)
	at compojure.core$routing.doInvoke(core.clj:182)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:662)
	at compojure.core$routes$fn__2401.invoke(core.clj:192)
	at territory_bro.infra.middleware$wrap_auto_refresh_projections$fn__18994.invoke(middleware.clj:74)
	at territory_bro.infra.middleware$wrap_sqlexception_chain$fn__18980.invoke(middleware.clj:38)
	at ring.middleware.http_response$wrap_http_response$fn__14946.invoke(http_response.clj:19)
	at ring.middleware.format_params$wrap_format_params$fn__14534.invoke(format_params.clj:113)
	at ring.middleware.format_params$wrap_format_params$fn__14534.invoke(format_params.clj:113)
	at ring.middleware.format_params$wrap_format_params$fn__14534.invoke(format_params.clj:113)
	at ring.middleware.format_response$wrap_format_response$fn__14847.invoke(format_response.clj:175)
	at territory_bro.infra.middleware$wrap_default_content_type$fn__18984.invoke(middleware.clj:51)
	at territory_bro.ui.error_page$wrap_error_pages$fn__18967.invoke(error_page.clj:38)
	at ring.logger$wrap_log_response$fn__13001.invoke(logger.clj:159)
	at ring.logger$wrap_log_request_params$fn__12982.invoke(logger.clj:64)
	at ring.logger$wrap_log_request_start$fn__12988.invoke(logger.clj:99)
	at ring.middleware.session$wrap_session$fn__13254.invoke(session.clj:112)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__13339.invoke(keyword_params.clj:53)
	at ring.middleware.nested_params$wrap_nested_params$fn__13389.invoke(nested_params.clj:89)
	at ring.middleware.multipart_params$handle_request_and_errors$fn__13620$fn__13621.invoke(multipart_params.clj:136)
	at ring.middleware.multipart_params$handle_request_and_errors.invokeStatic(multipart_params.clj:134)
	at ring.middleware.multipart_params$handle_request_and_errors.invoke(multipart_params.clj:133)
	at ring.middleware.multipart_params$wrap_multipart_params$fn__13626.invoke(multipart_params.clj:188)
	at ring.middleware.params$wrap_params$fn__13655.invoke(params.clj:75)
	at ring.middleware.cookies$wrap_cookies$fn__13216.invoke(cookies.clj:198)
	at ring.middleware.resource$wrap_resource_prefer_resources$fn__13663.invoke(resource.clj:25)
	at ring.middleware.content_type$wrap_content_type$fn__13724.invoke(content_type.clj:34)
	at ring.middleware.default_charset$wrap_default_charset$fn__13740.invoke(default_charset.clj:31)
	at ring.middleware.not_modified$wrap_not_modified$fn__13713.invoke(not_modified.clj:61)
	at ring.middleware.x_headers$wrap_x_header$fn__13023.invoke(x_headers.clj:22)
	at ring.middleware.x_headers$wrap_x_header$fn__13023.invoke(x_headers.clj:22)
	at ring.middleware.ssl$wrap_forwarded_scheme$fn__13770.invoke(ssl.clj:35)
	at ring.middleware.proxy_headers$wrap_forwarded_remote_addr$fn__13800.invoke(proxy_headers.clj:20)
	at territory_bro.infra.middleware$wrap_cache_control$fn__19000.invoke(middleware.clj:88)
	at territory_bro.infra.middleware$wrap_internal_error$fn__18975.invoke(middleware.clj:25)
	at clojure.lang.Var.invoke(Var.java:386)
	at ring.adapter.jetty$proxy_handler$fn__28401.invoke(jetty.clj:107)
	at ring.adapter.jetty.proxy$org.eclipse.jetty.servlet.ServletHandler$ff19274a.doHandle(Unknown Source)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
	at ring.adapter.jetty.proxy$org.eclipse.jetty.servlet.ServletHandler$ff19274a.doScope(Unknown Source)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:822)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.auth0.exception.APIException: Request failed with status code 403: The redirect URI is wrong. You sent https://beta.territorybro.com:80, and we expected https://beta.territorybro.com
	at com.auth0.net.ExtendedBaseRequest.createResponseException(ExtendedBaseRequest.java:131)
	at com.auth0.net.ExtendedBaseRequest.parseResponse(ExtendedBaseRequest.java:66)
	at com.auth0.net.BaseRequest.execute(BaseRequest.java:35)
	at com.auth0.RequestProcessor.exchangeCodeForTokens(RequestProcessor.java:349)
	at com.auth0.RequestProcessor.getVerifiedTokens(RequestProcessor.java:226)
	... 90 common frames omitted