🥅 The app should start even if calculating memory usage fails
Why:
- The CI build failed with the following exception:

java.lang.IllegalArgumentException: Some root is null
	at org.openjdk.jol.info.AbstractGraphWalker.verifyRoots(AbstractGraphWalker.java:46)
	at org.openjdk.jol.info.GraphWalker.walk(GraphWalker.java:51)
	at org.openjdk.jol.info.GraphLayout.parseInstance(GraphLayout.java:54)
	at territory_bro.projections$memory_usage.invokeStatic(projections.clj:99)
	at territory_bro.projections$memory_usage.invoke(projections.clj:75)
	at territory_bro.main$start_app.invokeStatic(main.clj:62)
	at territory_bro.main$start_app.invoke(main.clj:50)
	at territory_bro.main$_main.invokeStatic(main.clj:67)
	at territory_bro.main$_main.doInvoke(main.clj:65)
	at clojure.lang.RestFn.invoke(RestFn.java:400)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:135)
	at territory_bro.main.main(Unknown Source)