🐛 Fix too many open files
Why:
- The call to java.net.URLConnection#getLastModified() leaked resources,
  even though URLConnection doesn't have a close() method. Its
  documentation says:
    "Invoking the close() methods on the InputStream or OutputStream of
     an URLConnection after a request may free network resources
     associated with this instance, unless particular protocol
     specifications specify different behaviours for it."
- After the test runner and REPL had been on for days, Jetty started
  giving "java.io.IOException: Too many open files" errors. Inspecting
  the open files in Activity Monitor revealed lots of instances of files
  managed by the auto-refresher (e.g. i18n.json and the HugSQL files).

Example error:

2024-03-21 23:29:18,262 [qtp285145040-47-acceptor-1@323bdab7-ServerConnector@1e0a9b1a{HTTP/1.1, (http/1.1)}{0.0.0.0:8081}] WARN  o.e.jetty.server.AbstractConnector - Accept Failure
java.io.IOException: Too many open files
	at java.base/sun.nio.ch.Net.accept(Native Method)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.implAccept(ServerSocketChannelImpl.java:425)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:391)
	at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:409)
	at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:748)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:840)