🐛 Fix deadlock when generating multiple QR codes in parallel
Why:
- The SPA UI makes only one request to generate all QR codes. The SSR UI
  makes one request per QR codes. This causes lots of concurrent
  requests, which triggered a deadlock in the QR code generator.
- The prepare_new_event trigger locks the event table to ensure a single
  writer, and normally that is enough to avoid transaction conflicts.
  But since territory-bro.api/generate-qr-code! reads the event table
  (in current-state-for-request) before writing to it, the transaction
  acquires an ACCESS SHARE lock on the table. Then when concurrent
  transactions try to promote their locks to SHARE ROW EXCLUSIVE, it
  creates a deadlock.
- The solution is to acquire the SHARE ROW EXCLUSIVE first, before
  reading the table. Then the concurrent transactions will block before
  doing anything else, and won't create a cyclic dependency on each
  other and deadlock.

2024-07-12 21:11:54,835 [qtp832702336-90] WARN  territory-bro.dispatcher - Command failed: org.postgresql.util.PSQLException: ERROR: deadlock detected
  Detail: Process 163 waits for ShareRowExclusiveLock on relation 20140 of database 16384; blocked by process 162.
Process 162 waits for ShareRowExclusiveLock on relation 20140 of database 16384; blocked by process 163.
  Hint: See server log for query details.
  Where: SQL statement "lock table territorybro.event in share row exclusive mode"
PL/pgSQL function prepare_new_event() line 9 at SQL statement
2024-07-12 21:11:54,835 [qtp832702336-90] WARN  territory-bro.api - Deadlock detected: {:command/type :share.command/create-share, :share/id #uuid "9159c197-fec7-4c29-bc1b-506782e04b9b", :share/key 9F_9L51gImA, :share/type :qr-code, :congregation/id #uuid "89f8bcde-fa65-47cb-b5cc-9b11d01e410d", :territory/id #uuid "d7579f69-d312-4443-9a73-44974722d1e3", :command/time #object[java.time.Instant 0x7b5c7b71 2024-07-12T18:11:54.798809Z], :command/user #uuid "b86105a3-a8bc-46fe-84b6-01a8d3fd2719"}
org.postgresql.util.PSQLException: ERROR: deadlock detected
  Detail: Process 163 waits for ShareRowExclusiveLock on relation 20140 of database 16384; blocked by process 162.
Process 162 waits for ShareRowExclusiveLock on relation 20140 of database 16384; blocked by process 163.
  Hint: See server log for query details.
  Where: SQL statement "lock table territorybro.event in share row exclusive mode"
PL/pgSQL function prepare_new_event() line 9 at SQL statement
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:194)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:137)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:1090)
	at clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:1084)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1106)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1093)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1182)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1160)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:671)
	at clojure.core$apply.invoke(core.clj:662)
	at hugsql.adapter.clojure_java_jdbc.HugsqlAdapterClojureJavaJdbc.query(clojure_java_jdbc.clj:15)
	at hugsql.adapter$eval8165$fn__8181$G__8147__8186.invoke(adapter.clj:3)
	at hugsql.adapter$eval8165$fn__8181$G__8146__8192.invoke(adapter.clj:3)
	at clojure.lang.Var.invoke(Var.java:401)
	at hugsql.core$db_fn_STAR_$y__9940.doInvoke(core.clj:472)
	at clojure.lang.RestFn.invoke(RestFn.java:448)
	at hugsql.core$db_fn_STAR_$y__9940.invoke(core.clj:462)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.RestFn.applyTo(RestFn.java:135)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:662)
	at territory_bro.infra.db$query_BANG_.invokeStatic(db.clj:256)
	at territory_bro.infra.db$query_BANG_.invoke(db.clj:240)
	at territory_bro.infra.db$compile_queries$fn__35099.doInvoke(db.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:445)
	at territory_bro.infra.event_store$save_event_BANG_.invokeStatic(event_store.clj:61)
	at territory_bro.infra.event_store$save_event_BANG_.invoke(event_store.clj:59)
	at territory_bro.infra.event_store$save_BANG_$fn__35873.invoke(event_store.clj:81)
	at clojure.core$map_indexed$mapi__8676$fn__8677.invoke(core.clj:7500)
	at clojure.lang.LazySeq.force(LazySeq.java:50)
	at clojure.lang.LazySeq.realize(LazySeq.java:89)
	at clojure.lang.LazySeq.seq(LazySeq.java:106)
	at clojure.lang.RT.seq(RT.java:555)
	at clojure.core$seq__5484.invokeStatic(core.clj:139)
	at clojure.core$dorun.invokeStatic(core.clj:3141)
	at clojure.core$doall.invokeStatic(core.clj:3156)
	at clojure.core$doall.invoke(core.clj:3156)
	at territory_bro.infra.event_store$save_BANG_.invokeStatic(event_store.clj:87)
	at territory_bro.infra.event_store$save_BANG_.invoke(event_store.clj:73)
	at territory_bro.dispatcher$append_stream_BANG_.invokeStatic(dispatcher.clj:82)
	at territory_bro.dispatcher$append_stream_BANG_.invoke(dispatcher.clj:79)
	at territory_bro.dispatcher$share_command_BANG_.invokeStatic(dispatcher.clj:148)
	at territory_bro.dispatcher$share_command_BANG_.invoke(dispatcher.clj:146)
	at territory_bro.dispatcher$command_BANG_.invokeStatic(dispatcher.clj:186)
	at territory_bro.dispatcher$command_BANG_.invoke(dispatcher.clj:178)
	at territory_bro.api$dispatch_BANG_.invokeStatic(api.clj:292)
	at territory_bro.api$dispatch_BANG_.invoke(api.clj:289)
	at territory_bro.api$generate_qr_code_BANG_.invokeStatic(api.clj:440)
	at territory_bro.api$generate_qr_code_BANG_.invoke(api.clj:437)
	at territory_bro.api$generate_qr_codes$fn__36753$fn__36767$iter__36768__36772$fn__36773$fn__36774.invoke(api.clj:470)
	at territory_bro.api$generate_qr_codes$fn__36753$fn__36767$iter__36768__36772$fn__36773.invoke(api.clj:468)
	at clojure.lang.LazySeq.force(LazySeq.java:50)
	at clojure.lang.LazySeq.realize(LazySeq.java:89)
	at clojure.lang.LazySeq.seq(LazySeq.java:106)
	at clojure.lang.RT.seq(RT.java:555)
	at clojure.core$seq__5484.invokeStatic(core.clj:139)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24)
	at clojure.core.protocols$fn__8258.invokeStatic(protocols.clj:74)
	at clojure.core.protocols$fn__8258.invoke(protocols.clj:74)
	at clojure.core.protocols$fn__8199$G__8194__8212.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6965)
	at clojure.core$into.invokeStatic(core.clj:7038)
	at clojure.core$into.invoke(core.clj:7029)
	at territory_bro.api$generate_qr_codes$fn__36753$fn__36767.invoke(api.clj:468)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:807)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:852)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
	at territory_bro.api$generate_qr_codes$fn__36753.invoke(api.clj:464)
	at territory_bro.infra.authentication$with_user_STAR_.invokeStatic(authentication.clj:34)
	at territory_bro.infra.authentication$with_user_STAR_.invoke(authentication.clj:31)
	at territory_bro.api$generate_qr_codes.invokeStatic(api.clj:449)
	at territory_bro.api$generate_qr_codes.invoke(api.clj:448)
	at territory_bro.ui.printouts_page$fn__44708.invokeStatic(printouts_page.clj:234)
	at territory_bro.ui.printouts_page$fn__44708.invoke(printouts_page.clj:232)
	at territory_bro.ui.html$wrap_page_path$fn__36927.invoke(html.clj:83)
	at territory_bro.ui$wrap_json_api_compat$fn__47765.invoke(ui.clj:30)
	at ring.middleware.http_response$wrap_http_response$fn__13545.invoke(http_response.clj:19)
	at territory_bro.ui$wrap_current_user$fn__47768$fn__47769.invoke(ui.clj:35)
	at territory_bro.infra.authentication$with_user_STAR_.invokeStatic(authentication.clj:34)
	at territory_bro.infra.authentication$with_user_STAR_.invoke(authentication.clj:31)
	at territory_bro.ui$wrap_current_user$fn__47768.invoke(ui.clj:34)
	at territory_bro.ui.i18n$wrap_current_language$fn__37037.invoke(i18n.clj:48)
	at territory_bro.infra.auth0$wrap_redirect_to_login$fn__36884.invoke(auth0.clj:108)
	at territory_bro.ui.html$wrap_page_path$fn__36927.invoke(html.clj:83)
	at reitit.ring$ring_handler$fn__24175.invoke(ring.cljc:357)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:33)
	at clojure.lang.RestFn.invoke(RestFn.java:411)
	at clojure.lang.Var.invoke(Var.java:386)
	at compojure.core$routing$fn__13389.invoke(core.clj:185)
	at clojure.core$some.invokeStatic(core.clj:2718)
	at clojure.core$some.invoke(core.clj:2709)
	at compojure.core$routing.invokeStatic(core.clj:185)
	at compojure.core$routing.doInvoke(core.clj:182)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:662)
	at compojure.core$routes$fn__13393.invoke(core.clj:192)
	at compojure.core$wrap_routes$fn__13494.invoke(core.clj:353)
	at compojure.core$wrap_routes$fn__13494.invoke(core.clj:353)
	at territory_bro.infra.middleware$wrap_auto_refresh_projections$fn__40894.invoke(middleware.clj:74)
	at ring.middleware.reload$wrap_reload$fn__19505.invoke(reload.clj:39)
	at territory_bro.infra.middleware$wrap_sqlexception_chain$fn__40880.invoke(middleware.clj:38)
	at ring.middleware.http_response$wrap_http_response$fn__13545.invoke(http_response.clj:19)
	at territory_bro.infra.middleware$wrap_default_content_type$fn__40884.invoke(middleware.clj:51)
	at territory_bro.ui.error_page$wrap_error_pages$fn__40859.invoke(error_page.clj:38)
	at ring.logger$wrap_log_response$fn__16902.invoke(logger.clj:159)
	at ring.logger$wrap_log_request_params$fn__16883.invoke(logger.clj:64)
	at ring.logger$wrap_log_request_start$fn__16889.invoke(logger.clj:99)
	at ring.middleware.session$wrap_session$fn__17225.invoke(session.clj:112)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__17346.invoke(keyword_params.clj:53)
	at ring.middleware.nested_params$wrap_nested_params$fn__17404.invoke(nested_params.clj:89)
	at ring.middleware.multipart_params$handle_request_and_errors$fn__17707$fn__17708.invoke(multipart_params.clj:136)
	at ring.middleware.multipart_params$handle_request_and_errors.invokeStatic(multipart_params.clj:134)
	at ring.middleware.multipart_params$handle_request_and_errors.invoke(multipart_params.clj:133)
	at ring.middleware.multipart_params$wrap_multipart_params$fn__17713.invoke(multipart_params.clj:188)
	at ring.middleware.params$wrap_params$fn__17750.invoke(params.clj:75)
	at ring.middleware.cookies$wrap_cookies$fn__17175.invoke(cookies.clj:198)
	at ring.middleware.resource$wrap_resource_prefer_resources$fn__17766.invoke(resource.clj:25)
	at ring.middleware.content_type$wrap_content_type$fn__17851.invoke(content_type.clj:34)
	at ring.middleware.default_charset$wrap_default_charset$fn__17875.invoke(default_charset.clj:31)
	at ring.middleware.not_modified$wrap_not_modified$fn__17832.invoke(not_modified.clj:61)
	at ring.middleware.x_headers$wrap_x_header$fn__16938.invoke(x_headers.clj:22)
	at ring.middleware.x_headers$wrap_x_header$fn__16938.invoke(x_headers.clj:22)
	at ring.middleware.ssl$wrap_forwarded_scheme$fn__17921.invoke(ssl.clj:35)
	at ring.middleware.proxy_headers$wrap_forwarded_remote_addr$fn__17959.invoke(proxy_headers.clj:20)
	at territory_bro.infra.middleware$wrap_cache_control$fn__40900.invoke(middleware.clj:88)
	at territory_bro.infra.middleware$wrap_internal_error$fn__40875.invoke(middleware.clj:25)
	at clojure.lang.Var.invoke(Var.java:386)
	at ring.adapter.jetty$proxy_handler$fn__1818.invoke(jetty.clj:107)
	at ring.adapter.jetty.proxy$org.eclipse.jetty.servlet.ServletHandler$ff19274a.doHandle(Unknown Source)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
	at ring.adapter.jetty.proxy$org.eclipse.jetty.servlet.ServletHandler$ff19274a.doScope(Unknown Source)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:822)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:840)