🐛 Fix crash when a geometry intersects with itself
Why:
- Geometry union will fail if the geometries are not valid. A typical
  cause of invalid geometry is a polygon with a self-intersection. JTS
  will then throw an exception like the following:

org.locationtech.jts.geom.TopologyException: found non-noded intersection between LINESTRING ( 0 0, 1 1 ) and LINESTRING ( 1 0, 0 1 ) [ (0.5, 0.5, NaN) ]
 at org.locationtech.jts.noding.FastNodingValidator.checkValid (FastNodingValidator.java:139)
    org.locationtech.jts.geomgraph.EdgeNodingValidator.checkValid (EdgeNodingValidator.java:80)
    org.locationtech.jts.geomgraph.EdgeNodingValidator.checkValid (EdgeNodingValidator.java:45)
    org.locationtech.jts.operation.overlay.OverlayOp.computeOverlay (OverlayOp.java:229)
    org.locationtech.jts.operation.overlay.OverlayOp.getResultGeometry (OverlayOp.java:181)
    org.locationtech.jts.operation.overlay.OverlayOp.overlayOp (OverlayOp.java:84)
    org.locationtech.jts.operation.overlay.snap.SnapIfNeededOverlayOp.getResultGeometry (SnapIfNeededOverlayOp.java:75)
    org.locationtech.jts.operation.overlay.snap.SnapIfNeededOverlayOp.overlayOp (SnapIfNeededOverlayOp.java:37)
    org.locationtech.jts.geom.GeometryOverlay.overlay (GeometryOverlay.java:76)
    org.locationtech.jts.geom.GeometryOverlay.union (GeometryOverlay.java:157)
    org.locationtech.jts.geom.Geometry.union (Geometry.java:1369)
    territory_bro.gis.geometry$union$invoke__Geometry__DOT_union__3537657.invoke (geometry.clj:49)
    ...
    territory_bro.gis.geometry$union.invokeStatic (geometry.clj:51)
    territory_bro.gis.geometry$union.invoke (geometry.clj:49)

- JTS contains a GeometryFixer class which can be used to fix invalid
  geometries automatically. An older fix was to call Geometry.buffer(0),
  but that will lose part of the polygon. Related issues:
    https://github.com/locationtech/jts/issues/657
    https://github.com/locationtech/jts/issues/652
- This commit also improves logging when there is a crash in the
  projections. Debugging them is easier when the error message shows
  which event caused the crash.